//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEEIPro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public int dId { get; set; }
        public string departmentName { get; set; }
        public string departmentInfo { get; set; }
        public Nullable<System.DateTime> setUptime { get; set; }
        public Nullable<int> isDel { get; set; }
    }
}
