//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEEIPro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public int exlId { get; set; }
        public string name { get; set; }
        public string fileSize { get; set; }
        public string downloadLink { get; set; }
        public Nullable<System.DateTime> uploadTime { get; set; }
        public Nullable<int> uploader { get; set; }
        public Nullable<int> downloadCounts { get; set; }
        public string docType { get; set; }
        public Nullable<int> isOpen { get; set; }
        public Nullable<int> isDel { get; set; }
    }
}
