//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEEIPro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expert
    {
        public int sId { get; set; }
        public string eId { get; set; }
        public string eName { get; set; }
        public string gender { get; set; }
        public Nullable<System.DateTime> birthDay { get; set; }
        public string identityNumber { get; set; }
        public Nullable<int> unitProperty { get; set; }
        public string UnitDetailsOne { get; set; }
        public string UnitDetailsTwo { get; set; }
        public string UnitDetailsThree { get; set; }
        public string academicTitles { get; set; }
        public string field { get; set; }
        public string email { get; set; }
        public string officePhone { get; set; }
        public string cellPhone { get; set; }
        public string postalAddress { get; set; }
        public string expertSources { get; set; }
        public Nullable<int> beStatus { get; set; }
        public string img { get; set; }
        public string personalUrl { get; set; }
        public string Categories { get; set; }
        public string registrationForm { get; set; }
        public string appointmentBook { get; set; }
        public string SerialNum { get; set; }
        public string remark { get; set; }
        public string expertIntroduction { get; set; }
        public string expertworkingExperience { get; set; }
        public string expertAchievement { get; set; }
        public Nullable<System.DateTime> addTime { get; set; }
    }
}
