//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEEIPro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpertExperience
    {
        public int id { get; set; }
        public string serialId { get; set; }
        public string title { get; set; }
        public Nullable<System.DateTime> time { get; set; }
        public string address { get; set; }
        public string pdffiles { get; set; }
        public string video { get; set; }
    }
}
