//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEEIPro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpertBankInfo
    {
        public int id { get; set; }
        public string serialId { get; set; }
        public string accountName { get; set; }
        public string acountNumber { get; set; }
        public string bankName { get; set; }
        public string remark { get; set; }
    }
}
