//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEEIPro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public int nId { get; set; }
        public string newsTitle { get; set; }
        public string newsOutline { get; set; }
        public string titleImgUrl { get; set; }
        public string newsContent { get; set; }
        public Nullable<System.DateTime> addTime { get; set; }
        public Nullable<int> readCounts { get; set; }
        public Nullable<int> newsType { get; set; }
        public Nullable<int> announcer { get; set; }
        public Nullable<int> isDel { get; set; }
    }
}
