//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEEIPro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Privilege
    {
        public int lid { get; set; }
        public string privilegename { get; set; }
        public string remark { get; set; }
    }
}
