//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEEIPro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public int sId { get; set; }
        public string name { get; set; }
        public string gender { get; set; }
        public Nullable<System.DateTime> birthdate { get; set; }
        public string telphone { get; set; }
        public string email { get; set; }
        public string nativePlace { get; set; }
        public string salaryCard { get; set; }
        public string mailingAddress { get; set; }
        public string userName { get; set; }
        public string passWord { get; set; }
        public string position { get; set; }
        public Nullable<int> departId { get; set; }
        public Nullable<int> isDel { get; set; }
        public Nullable<int> privilegeLevel { get; set; }
        public Nullable<System.DateTime> entryDate { get; set; }
    }
}
